name: .NET
env:
  NAME: 'prod'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Directus.SDK/Directus.SDK.csproj

      - name: Build
        run: dotnet build Directus.SDK/Directus.SDK.csproj --no-restore -c Release

      - name: Pack
        run: dotnet pack Directus.SDK/Directus.SDK.csproj --no-build -c Release -o ./nupkg

      - name: Publish to NuGet
        run: 
          dotnet nuget push "./nupkg/*.nupkg"  --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"
